# Generated by Django 4.2.2 on 2023-06-21 14:11

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Makro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('protein', models.DecimalField(decimal_places=2, max_digits=32)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=32)),
                ('carbohydrate', models.DecimalField(decimal_places=2, max_digits=32)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('intake', models.DecimalField(decimal_places=2, max_digits=32)),
                ('unit_name', models.CharField(max_length=128)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodNutrient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=32)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('nutrient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.nutrient')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=256)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('food_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.foodcategory')),
                ('makros', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.makro')),
                ('nutritions', models.ManyToManyField(blank=True, related_name='nutritions', to='base.foodnutrient')),
            ],
        ),
    ]
